### ISSUE TITLE
Thrown Antimatter is broken

### ISSUE THREAD

**Issue by Mutantoe** [Mutantoe/Anti-Minecraft#1]
Log:

[19:42:13] [main/INFO] [GradleStart]: username: Mutantoe
[19:42:13] [main/INFO] [GradleStart]: Extra: []
[19:42:13] [main/INFO] [GradleStart]: Running with arguments: [--userProperties, {}, --assetsDir, C:/Users/Joe/.gradle/caches/minecraft/assets, --assetIndex, 1.8, --accessToken, {REDACTED}, --version, 1.8, --username, Mutantoe, --tweakClass, net.minecraftforge.fml.common.launcher.FMLTweaker, --tweakClass, net.minecraftforge.gradle.GradleStartCommon$GradleStartTweaker]
[19:42:13] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[19:42:13] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[19:42:13] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.gradle.GradleStartCommon$GradleStartTweaker
[19:42:13] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[19:42:13] [main/INFO] [FML]: Forge Mod Loader version 8.0.37.1329 for Minecraft 1.8 loading
[19:42:13] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_31, running on Windows 7:amd64:6.1, installed at C:\Program Files\Java\jre1.8.0_31
[19:42:13] [main/INFO] [FML]: Managed to load a deobfuscated Minecraft name- we are in a deobfuscated environment. Skipping runtime deobfuscation
[19:42:13] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.gradle.GradleStartCommon$GradleStartTweaker
[19:42:13] [main/INFO] [GradleStart]: Injecting location in coremod net.minecraftforge.fml.relauncher.FMLCorePlugin
[19:42:13] [main/INFO] [GradleStart]: Injecting location in coremod net.minecraftforge.classloading.FMLForgePlugin
[19:42:13] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:42:13] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[19:42:13] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:42:13] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:42:13] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:42:14] [main/ERROR] [FML]: The binary patch set is missing. Either you are in a development environment, or things are not going to work!
[19:42:17] [main/ERROR] [FML]: FML appears to be missing any signature data. This is not a good thing
[19:42:17] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:42:17] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[19:42:17] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[19:42:17] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[19:42:17] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[19:42:18] [Client thread/INFO]: Setting user: Mutantoe
[19:42:22] [Client thread/INFO]: LWJGL Version: 2.9.1
[19:42:23] [Client thread/INFO] [MinecraftForge]: Attempting early MinecraftForge initialization
[19:42:23] [Client thread/INFO] [FML]: MinecraftForge v11.14.1.1329 Initialized
[19:42:23] [Client thread/INFO] [FML]: Replaced 204 ore recipies
[19:42:23] [Client thread/INFO] [MinecraftForge]: Completed early MinecraftForge initialization
[19:42:23] [Client thread/INFO] [FML]: Searching C:\Users\Joe\Documents\GitHub\Anti-Minecraft\eclipse\mods for mods
[19:42:25] [Client thread/INFO] [FML]: Forge Mod Loader has identified 4 mods to load
[19:42:26] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, AMC] at CLIENT
[19:42:26] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, AMC] at SERVER
[19:42:26] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Anti-Minecraft
[19:42:26] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[19:42:26] [Client thread/INFO] [FML]: Found 384 ObjectHolder annotations
[19:42:26] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[19:42:26] [Client thread/INFO] [AMC]: Loading Anti-Minecraft Version: 1.0
[19:42:26] [Client thread/INFO] [FML]: Applying holder lookups
[19:42:26] [Client thread/INFO] [FML]: Holder lookups applied
[19:42:27] [Sound Library Loader/INFO]: Starting up SoundSystem...
[19:42:27] [Thread-7/INFO]: Initializing LWJGL OpenAL
[19:42:27] [Thread-7/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[19:42:28] [Thread-7/INFO]: OpenAL initialized.
[19:42:28] [Sound Library Loader/INFO]: Sound engine started
[19:42:35] [Client thread/INFO]: Created: 512x512 textures-atlas
[19:42:37] [Client thread/INFO] [FML]: Forge Mod Loader has successfully loaded 4 mods
[19:42:37] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Anti-Minecraft
[19:42:37] [Client thread/INFO]: SoundSystem shutting down...
[19:42:37] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
[19:42:37] [Sound Library Loader/INFO]: Starting up SoundSystem...
[19:42:37] [Thread-9/INFO]: Initializing LWJGL OpenAL
[19:42:37] [Thread-9/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[19:42:38] [Thread-9/INFO]: OpenAL initialized.
[19:42:38] [Sound Library Loader/INFO]: Sound engine started
[19:42:44] [Client thread/INFO]: Created: 512x512 textures-atlas
[19:42:49] [Server thread/INFO]: Starting integrated minecraft server version 1.8
[19:42:49] [Server thread/INFO]: Generating keypair
[19:42:49] [Server thread/INFO] [FML]: Injecting existing block and item data into this server instance
[19:42:49] [Server thread/INFO] [FML]: Applying holder lookups
[19:42:49] [Server thread/INFO] [FML]: Holder lookups applied
[19:42:49] [Server thread/INFO] [FML]: Loading dimension 0 (New World) (net.minecraft.server.integrated.IntegratedServer@5c46d681)
[19:42:49] [Server thread/INFO] [FML]: Loading dimension 1 (New World) (net.minecraft.server.integrated.IntegratedServer@5c46d681)
[19:42:49] [Server thread/INFO] [FML]: Loading dimension -1 (New World) (net.minecraft.server.integrated.IntegratedServer@5c46d681)
[19:42:49] [Server thread/INFO]: Preparing start region for level 0
[19:42:50] [Server thread/INFO]: Preparing spawn area: 29%
[19:42:52] [Server thread/INFO]: Changing view distance to 12, from 10
[19:42:52] [Netty Local Client IO #0/INFO] [FML]: Server protocol version 1
[19:42:52] [Netty Server IO #1/INFO] [FML]: Client protocol version 1
[19:42:52] [Netty Server IO #1/INFO] [FML]: Client attempting to join with 4 mods : FML@8.0.37.1329,AMC@1.0,Forge@11.14.1.1329,mcp@9.05
[19:42:52] [Netty Local Client IO #0/INFO] [FML]: [Netty Local Client IO #0] Client side modded connection established
[19:42:52] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[19:42:52] [Server thread/INFO]: Mutantoe[local:E:8aeb33e0] logged in with entity id 188 at (-1.5, 71.0, 248.5)
[19:42:52] [Server thread/INFO]: Mutantoe joined the game
[19:43:00] [Server thread/INFO] [AMC]: THROW
[19:43:01] [Server thread/INFO]: Stopping server
[19:43:01] [Server thread/INFO]: Saving players
[19:43:01] [Server thread/INFO]: Saving worlds
[19:43:01] [Server thread/INFO]: Saving chunks for level 'New World'/Overworld
[19:43:01] [Server thread/INFO]: Saving chunks for level 'New World'/Nether
[19:43:01] [Server thread/INFO]: Saving chunks for level 'New World'/The End
[19:43:02] [Server thread/INFO] [FML]: Unloading dimension 0
[19:43:02] [Server thread/INFO] [FML]: Unloading dimension -1
[19:43:02] [Server thread/INFO] [FML]: Unloading dimension 1
[19:43:02] [Server thread/INFO] [FML]: Applying holder lookups
[19:43:02] [Server thread/INFO] [FML]: Holder lookups applied
[19:43:03] [Client thread/FATAL]: Unreported exception thrown!
java.lang.ClassCastException: com.mutantoe.amin.entity.EntityAntimatter cannot be cast to net.minecraft.entity.EntityLiving
	at net.minecraft.client.renderer.entity.RenderLiving.shouldRender(RenderLiving.java:204) ~[RenderLiving.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.shouldRender(RenderManager.java:307) ~[RenderManager.class:?]
	at net.minecraft.client.renderer.RenderGlobal.renderEntities(RenderGlobal.java:645) ~[RenderGlobal.class:?]
	at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1350) ~[EntityRenderer.class:?]
	at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1263) ~[EntityRenderer.class:?]
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1088) ~[EntityRenderer.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1107) ~[Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:376) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:117) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:85) [start/:?]
	at GradleStart.main(GradleStart.java:45) [start/:?]
[19:43:03] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:printToSYSOUT:660]: ---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 25/02/15 19:43
Description: Unexpected error

java.lang.ClassCastException: com.mutantoe.amin.entity.EntityAntimatter cannot be cast to net.minecraft.entity.EntityLiving
	at net.minecraft.client.renderer.entity.RenderLiving.shouldRender(RenderLiving.java:204)
	at net.minecraft.client.renderer.entity.RenderManager.shouldRender(RenderManager.java:307)
	at net.minecraft.client.renderer.RenderGlobal.renderEntities(RenderGlobal.java:645)
	at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1350)
	at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1263)
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1088)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1107)
	at net.minecraft.client.Minecraft.run(Minecraft.java:376)
	at net.minecraft.client.main.Main.main(Main.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:85)
	at GradleStart.main(GradleStart.java:45)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderLiving.shouldRender(RenderLiving.java:204)
	at net.minecraft.client.renderer.entity.RenderManager.shouldRender(RenderManager.java:307)
	at net.minecraft.client.renderer.RenderGlobal.renderEntities(RenderGlobal.java:645)
	at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1350)
	at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1263)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Mutantoe'/188, l='MpServer', x=-6.64, y=76.75, z=267.59]]
	Chunk stats: MultiplayerChunkCache: 576, 576
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: 4.00,64.00,256.00 - World: (4,64,256), Chunk: (at 4,4,0 in 0,16; contains blocks 0,0,256 to 15,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 385 game time, 385 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 65 total; [EntityCreeper['Creeper'/1794, l='MpServer', x=71.50, y=30.02, z=255.50], EntityZombie['Zombie'/139, l='MpServer', x=59.50, y=21.00, z=245.31], EntityZombie['Zombie'/140, l='MpServer', x=57.50, y=38.00, z=266.50], EntityCreeper['Creeper'/157, l='MpServer', x=68.53, y=19.00, z=260.66], EntityCreeper['Creeper'/158, l='MpServer', x=67.50, y=19.00, z=258.50], EntityCreeper['Creeper'/159, l='MpServer', x=63.97, y=19.00, z=263.44], EntityCreeper['Creeper'/160, l='MpServer', x=72.50, y=20.00, z=262.50], EntityCreeper['Creeper'/161, l='MpServer', x=69.94, y=20.00, z=258.66], EntityBat['Bat'/162, l='MpServer', x=61.85, y=23.86, z=261.14], EntityBat['Bat'/163, l='MpServer', x=70.53, y=33.10, z=259.72], EntityCreeper['Creeper'/38, l='MpServer', x=-82.97, y=36.00, z=221.34], EntityCreeper['Creeper'/39, l='MpServer', x=-85.00, y=15.00, z=251.03], EntitySpider['Spider'/41, l='MpServer', x=-85.00, y=16.00, z=248.69], EntityBat['Bat'/46, l='MpServer', x=-85.80, y=49.33, z=291.52], EntityZombie['Zombie'/1840, l='MpServer', x=-84.50, y=13.02, z=216.50], EntityZombie['Zombie'/1843, l='MpServer', x=60.50, y=39.02, z=267.50], EntitySpider['Spider'/1845, l='MpServer', x=60.50, y=39.02, z=265.50], EntitySpider['Spider'/55, l='MpServer', x=-74.13, y=12.00, z=268.50], EntitySkeleton['Skeleton'/56, l='MpServer', x=-76.28, y=13.00, z=270.22], EntityZombie['Zombie'/57, l='MpServer', x=-73.81, y=48.00, z=258.53], EntitySkeleton['Skeleton'/58, l='MpServer', x=-68.50, y=22.00, z=289.50], EntityZombie['Zombie'/59, l='MpServer', x=-69.50, y=22.00, z=292.50], EntityPig['Pig'/60, l='MpServer', x=-68.84, y=63.00, z=337.31], EntityPig['Pig'/61, l='MpServer', x=-69.84, y=64.00, z=333.81], EntityPig['Pig'/62, l='MpServer', x=-66.31, y=64.00, z=332.28], EntityWitch['Witch'/64, l='MpServer', x=-59.50, y=55.00, z=257.84], EntityEnderman['Enderman'/65, l='MpServer', x=-60.78, y=22.00, z=290.47], EntityCreeper['Creeper'/66, l='MpServer', x=-50.50, y=38.00, z=335.50], EntityPig['Pig'/67, l='MpServer', x=-63.00, y=64.00, z=338.06], EntityAntimatter['entity.AMC.Antimatter.name'/1859, l='MpServer', x=-7.09, y=77.76, z=268.72], EntityPlayerSP['Mutantoe'/188, l='MpServer', x=-6.64, y=76.75, z=267.59], EntityCreeper['Creeper'/68, l='MpServer', x=-45.50, y=27.00, z=194.50], EntityCreeper['Creeper'/69, l='MpServer', x=-33.50, y=42.00, z=213.50], EntityCreeper['Creeper'/70, l='MpServer', x=-35.50, y=59.00, z=210.97], EntityBat['Bat'/71, l='MpServer', x=-45.31, y=26.74, z=264.74], EntityItem['item.item.seeds'/72, l='MpServer', x=-39.19, y=64.00, z=281.88], EntityPig['Pig'/81, l='MpServer', x=-18.47, y=77.00, z=204.22], EntityPig['Pig'/82, l='MpServer', x=-17.84, y=76.00, z=212.50], EntityPig['Pig'/83, l='MpServer', x=-17.50, y=75.00, z=214.50], EntityBat['Bat'/84, l='MpServer', x=-29.11, y=42.04, z=262.57], EntitySquid['Squid'/85, l='MpServer', x=-19.63, y=58.16, z=317.22], EntityPig['Pig'/94, l='MpServer', x=-14.50, y=78.00, z=214.50], EntityItem['item.item.seeds'/96, l='MpServer', x=-7.34, y=63.00, z=287.84], EntitySquid['Squid'/97, l='MpServer', x=-5.81, y=60.44, z=314.84], EntitySquid['Squid'/98, l='MpServer', x=-15.69, y=62.00, z=310.25], EntityBat['Bat'/1763, l='MpServer', x=20.44, y=16.56, z=310.13], EntitySquid['Squid'/99, l='MpServer', x=-13.22, y=62.38, z=321.28], EntitySkeleton['Skeleton'/100, l='MpServer', x=-8.50, y=36.00, z=336.09], EntityPig['Pig'/106, l='MpServer', x=14.41, y=78.00, z=231.50], EntityCreeper['Creeper'/107, l='MpServer', x=5.50, y=22.00, z=297.50], EntitySquid['Squid'/108, l='MpServer', x=11.56, y=59.19, z=298.63], EntityCreeper['Creeper'/1772, l='MpServer', x=-70.22, y=31.00, z=246.66], EntitySquid['Squid'/109, l='MpServer', x=16.19, y=58.91, z=303.34], EntitySquid['Squid'/110, l='MpServer', x=12.47, y=58.38, z=294.22], EntitySquid['Squid'/111, l='MpServer', x=7.56, y=57.34, z=298.88], EntityPig['Pig'/114, l='MpServer', x=21.34, y=65.02, z=238.50], EntityPig['Pig'/115, l='MpServer', x=16.50, y=76.00, z=230.44], EntityPig['Pig'/116, l='MpServer', x=17.52, y=77.00, z=228.61], EntityZombie['Zombie'/120, l='MpServer', x=35.50, y=15.00, z=233.50], EntityZombie['Zombie'/121, l='MpServer', x=37.38, y=15.00, z=232.84], EntitySkeleton['Skeleton'/122, l='MpServer', x=39.50, y=35.00, z=262.50], EntitySkeleton['Skeleton'/123, l='MpServer', x=36.50, y=35.00, z=265.50], EntitySkeleton['Skeleton'/124, l='MpServer', x=38.59, y=52.85, z=258.27], EntitySkeleton['Skeleton'/125, l='MpServer', x=43.50, y=50.00, z=262.50], EntityZombie['Zombie'/126, l='MpServer', x=43.31, y=50.00, z=261.66]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:392)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2600)
	at net.minecraft.client.Minecraft.run(Minecraft.java:405)
	at net.minecraft.client.main.Main.main(Main.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:85)
	at GradleStart.main(GradleStart.java:45)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_31, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 668211856 bytes (637 MB) / 1037959168 bytes (989 MB) up to 1037959168 bytes (989 MB)
	JVM Flags: 3 total; -Xincgc -Xmx1024M -Xms1024M
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP v9.10 FML v8.0.37.1329 Minecraft Forge 11.14.1.1329 4 mods loaded, 4 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{8.0.37.1329} [Forge Mod Loader] (forgeSrc-1.8-11.14.1.1329.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{11.14.1.1329} [Minecraft Forge] (forgeSrc-1.8-11.14.1.1329.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AMC{1.0} [Anti-Minecraft] (bin) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Loaded coremods (and transformers): 
	Launched Version: 1.8
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 3000 GL version 3.1.0 - Build 9.17.10.3347, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
[19:43:03] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:printToSYSOUT:660]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Joe\Documents\GitHub\Anti-Minecraft\eclipse\.\crash-reports\crash-2015-02-25_19.43.03-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

**Comment by Mutantoe** [comment]
Wierd: after reloading the world, the explosion has happened.

**Comment by Mutantoe** [comment]
Fixed
